version: '3.3'
services:
  traefik:
    container_name: traefik
    image: traefik:v2.4
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ./traefik_dynamic.toml:/traefik_dynamic.toml
      - ./acme.json:/acme.json
networks:
  web:
    external: true
