[http.middlewares.simpleAuth.basicAuth]
  users = [
    "admin:YOUR_ADMIN_PASSWORD"
  ]

[http.routers.api]
  rule = "Host(`SUBDOMAIN.YOUR-DOMAIN.COM`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"